# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

complexity:
  LongMethod:
    threshold: 120

formatting:
  MaximumLineLength:
    active: false

style:
  ReturnCount:
    excludeGuardClauses: true
